services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tasktracker-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HeladoAG0302@"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: